config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  root 'restaurants#index'

  resources :restaurants
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable

  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	belongs_to :owner

	validates_presence_of :name

	def is_owner?(an_owner)
		self.owner_id == an_owner.id
	rescue
		false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_create_params)
    if @restaurant.persisted?
      redirect_to(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = fetch_and_authorize_restaurant
  end

  def update
    @restaurant = fetch_and_authorize_restaurant
    if @restaurant.update_attributes(restaurant_params)
      redirect_to(@restaurant)
    else
      render :edit
    end
  end

  def show
    @restaurant = fetch_restaurant_by_id
  end

  def destroy
    @restaurant = fetch_and_authorize_restaurant
    @restaurant.destroy if @restaurant
    redirect_to restaurants_path 
  end

  private
  def fetch_and_authorize_restaurant
    restaurant = fetch_restaurant_by_id
    if restaurant.is_owner?(current_owner)
      restaurant
    else
      flash[:error] = "Unauthorized"
      redirect_to(restaurant)
    end
  end

  def fetch_restaurant_by_id
    Restaurant.find(params.fetch(:id))
  end

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :description,
      :address_1,
      :address_2,
      :phonne
      )
  end

  def restaurant_create_params
    restaurant_params.merge(owner: current_owner)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rest1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	Name: <%= f.text_field :name %>
	Description: <%= f.text_field :description %>
	Address 1: <%= f.text_field :address_1 %>
	Address 2: <%= f.text_field :address_2 %>
	Phone Number: <%= f.text_field :phone %>
	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>All of the restaurants</h1>
<h2><%= link_to 'Create a restaurant', new_restaurant_path %></h2>

<ul>
	<% @restaurants.each do |restaurant| %>
	<li>
		<span class="show">
			<%= link_to restaurant.name, restaurant %>
		</span>
		<% if restaurant.is_owner?(current_owner) %>
			<span class="edit">
				<%= link_to 'Edit', edit_restaurant_path(restaurant) %>
			</span>
			<span class="delete">
				<%= link_to 'Destroy', restaurant_path(restaurant), method: 'delete' %>
			</span>
		<% end %>
	</li>
	<% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>